server:
  port: 10001
spring:
  application:
    name: order.consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.126.147:8848
management:
  endpoints:
    web:
      exposure:
        include: info,health,beans,env

provider:
  order.provider: order.provider

