server:
  port: 11002
spring:
  application:
    name: order-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.126.147:8848
management:
  endpoints:
    web:
      exposure:
        include: info,health,beans,env
